Screen verstka
chikibrikie/HeroStats pull request #12
Opened 2024-01-18 20:27 UTC by chikibrikie

Сверстали грубо экраны. Добавили текста кнопки и инпуты.

2024-01-18 20:31 UTC, Apleeeee approved these changes
LGTM

2024-01-19 14:35 UTC, Bibazavr requested changes
Надо бы переименовать `SingIn -> SignIn` и добавить стилей, чтобы приложение выглядело +- как в дизайне

2024-01-19 16:55 UTC, Bibazavr requested changes

2024-01-19 16:55 UTC, Bibazavr commented on src/pages/Auth/ui/SignUpScreen.tsx
>      backgroundColor: "#fff",
Надо бы backgroudColor брать из темы paper-a

2024-01-21 10:09 UTC, Bibazavr requested changes
![image](https://github.com/chikibrikie/HeroStats/assets/51177449/ee4b84c1-caa9-4ac8-8072-a9a8010cc38e)
Прилипшую кнопку поправить и можно мержить)

2024-01-23 00:08 UTC, merged